# Polynomial Regression

### Import Libraries

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

### Define Data 

In [2]:
x = np.array([5,15,25,35,45,55]).reshape((-1,1)) # Input should be 2D
y = np.array([15,11,2,8,25,32])

### Transform Input Data 
- **degree** (integer) : Represents the Degree of **Polynomial Regression Function**.
- **include_bias** (boolean) : Include **Bias** Column (True) or Not (False)

In [3]:
x_transform = PolynomialFeatures(degree=2,include_bias=False).fit_transform(x)

### Create and Train Model

In [4]:
model = LinearRegression().fit(x_transform,y)

### Coefficient of Determination (R<sup>2</sup>)

In [5]:
R2 = model.score(x_transform,y)
print(f'Coefficient of Determination : {R2}')

Coefficient of Determination : 0.8908516262498563


### Slope and Intercept

In [6]:
print(f'Slope : {model.coef_}')
print(f'Intercept : {model.intercept_}')

Slope : [-1.32357143  0.02839286]
Intercept : 21.372321428571418


In [7]:
# Without Including Bias
print(f'Transformed x : \n{x_transform}')

Transformed x : 
[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


In [8]:
# Include Bias
x_transform = PolynomialFeatures(degree=2,include_bias=True).fit_transform(x)
print(f'Transformed x : \n{x_transform}')

Transformed x : 
[[1.000e+00 5.000e+00 2.500e+01]
 [1.000e+00 1.500e+01 2.250e+02]
 [1.000e+00 2.500e+01 6.250e+02]
 [1.000e+00 3.500e+01 1.225e+03]
 [1.000e+00 4.500e+01 2.025e+03]
 [1.000e+00 5.500e+01 3.025e+03]]


**Intercept** is already included with Left most Column of 1's (No need to Include it again)

In [9]:
model = LinearRegression(fit_intercept=False).fit(x_transform,y)
R2 = model.score(x_transform,y)
print(f'Coefficient of Determination : {R2}')
print(f'Slope : {model.coef_}')
print(f'Intercept : {model.intercept_}')

Coefficient of Determination : 0.8908516262498565
Slope : [21.37232143 -1.32357143  0.02839286]
Intercept : 0.0


### Prediction

In [10]:
y_pred = model.predict(x_transform)
print(f'Prediction : {y_pred}')

Prediction : [15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]
