# Simple Linear Regression

### Import Libraries

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

### Define Data 
- **reshape(-1,1)** : -1 indicates as many **Rows** as needed and 1 indicates **One Column**.
- **reshape(-1,1)** : Converts **1D** Array into **2D**.

In [2]:
x = np.array([5,15,25,35,45,55]).reshape((-1,1))
y = np.array([5,20,14,32,22,38])

In [3]:
print(f'x : \n{x}') # 2D Array 
print(f'\ny : {y}') # 1D Array

x : 
[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]

y : [ 5 20 14 32 22 38]


In [4]:
print(f'Shape of x : {x.shape[0]} Rows and {x.shape[1]} Column') 
print(f'Shape of y : {y.shape[0]} Rows') # Array of (6 Rows)

Shape of x : 6 Rows and 1 Column
Shape of y : 6 Rows


In [5]:
print(f'Dimensions of x : {x.ndim}D')
print(f'Dimensions of y : {y.ndim}D')

Dimensions of x : 2D
Dimensions of y : 1D


### Create and Train a Model
Important Parameters
1. **fit_intercept** (Boolean) : Whether Calculate Intercept(B0) (True) or Consider it Equal to Zero (False)
2. **normalize** (Boolean) : Whether to **Normalize** the Independent Variable (True) or not (False)

In [6]:
model = LinearRegression().fit(x,y)

### Coefficient of Determination (R<sup>2</sup>) 

In [7]:
R2 = model.score(x,y)
print(f'Coefficient of Determination : {R2}')

Coefficient of Determination : 0.715875613747954


### Slope and Intercept

In [8]:
print(f'Slope : {model.coef_}')
print(f'Intercept : {model.intercept_}')

Slope : [0.54]
Intercept : 5.633333333333333


In [9]:
type(model.coef_)

numpy.ndarray

### Predict Response

In [10]:
y_pred = model.predict(x) # Predict on Train Data 
print(f'Predictions : {y_pred}')

Predictions : [ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [11]:
# y = m(Slope) * x + c(Intercept)
y_pred = model.coef_ * x + model.intercept_
print(f'Predictions : \n{y_pred}')

Predictions : 
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [12]:
x_new = np.arange(5).reshape((-1,1))
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [13]:
# Prediction on New Data
y_new = model.predict(x_new)
print(f'Prediction on New Data : {y_new}')

Prediction on New Data : [5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
